"""Program content - all 5 sessions with exercises, cues, and voiceover scripts."""

# Program overview
PROGRAM = {
    "id": "cricket-comeback-12w",
    "title": "42+ HOME FITNESS COMEBACK",
    "subtitle": "12-Week Strength & Cricket Program",
    "total_weeks": 12,
    "phases": [
        {"name": "RECONDITION", "weeks": [1, 2, 3, 4], "focus": "Rebuild movement patterns, wake up the body"},
        {"name": "STRENGTH", "weeks": [5, 6, 7, 8], "focus": "Add load, push honest RIR 2-3"},
        {"name": "STRENGTH + ATHLETICISM", "weeks": [9, 10, 11, 12], "focus": "Layer power, keep injury risk low"},
    ],
    "weekly_schedule": [
        {"day": "MON", "label": "Recovery / Walk", "session_id": None},
        {"day": "TUE", "label": "Full Body Strength A", "session_id": "full-body-a"},
        {"day": "WED", "label": "Active Recovery / Walk", "session_id": None},
        {"day": "THU", "label": "Full Body Strength B", "session_id": "full-body-b"},
        {"day": "FRI", "label": "Mobility + Core", "session_id": "mobility-core"},
        {"day": "SAT", "label": "Cricket Match", "session_id": "cricket-day"},
        {"day": "SUN", "label": "Cricket Match", "session_id": "cricket-day"},
    ],
    "equipment": [
        "5-ft straight barbell",
        "3-ft curl (EZ) bar",
        "3 dumbbell handles",
        "Plates: 4 x 2.5 kg, 4 x 5 kg",
        "Bodyweight",
    ],
    "principles": [
        "Same weight across all 3 working sets.",
        "Leave 2-3 reps in the tank (RIR 2-3). No grinding.",
        "Clear the top of the rep range with clean form, then add the smallest plate next session.",
        "If a joint hurts, stop the set. Soreness fades; strains linger.",
    ],
}


def _blk(kind, **kw):
    return {"kind": kind, **kw}


# ---------- SESSION 1: INTRO ----------
SESSION_INTRO = {
    "id": "intro",
    "code": "S1",
    "title": "PROGRAM INTRO",
    "subtitle": "How To Use This Program",
    "day": None,
    "duration_min": 12,
    "color": "amber",
    "blocks": [
        _blk("title", heading="PROGRAM INTRO", sub="How To Use This Program", duration=6),
        _blk("say", heading="WELCOME BACK", body="This is a 12-week program built for a 42-year-old cricketer with a 5-year training gap. Calm, honest, no ego. We rebuild before we push.",
             voice="Welcome. This program is built for the weekend cricketer with real life on their plate. Twelve weeks. Two strength days, one mobility day, and match-day support. We rebuild first, then we get strong.", duration=10),
        _blk("say", heading="EQUIPMENT TOUR", body="One 5-foot straight bar. One 3-foot curl bar. Three dumbbell handles. Four 2.5 kg plates and four 5 kg plates. No bench, no rack. Everything is done from the floor or standing.",
             voice="Your kit is simple. A five-foot straight bar, a curl bar, three dumbbell handles, and plates up to twenty kilos a side. No bench, no rack. Every lift starts from the floor or standing.", duration=10),
        _blk("say", heading="SETS x REPS x RIR", body="Three working sets of the same weight. Rep range like 8 to 10. RIR 2 to 3 means: at the last rep, you had 2 or 3 more clean reps in reserve. Never grind.",
             voice="Three working sets at the same weight. Your rep range is a window, for example eight to ten. R I R two to three means you finish the set with two or three clean reps still in the tank. No grinding, ever.", duration=12),
        _blk("say", heading="PROGRESSIVE OVERLOAD", body="Clear the top of the rep range on all three sets with clean form. Next session, add the smallest plate. That is it. Slow, honest, boring, and it works.",
             voice="Progressive overload rule. When you clear the top of the rep range on all three sets with clean form, next session you add the smallest plate. Slow. Honest. It works.", duration=12),
        _blk("say", heading="12-WEEK PHASES", body="Weeks 1 to 4: RECONDITION. Weeks 5 to 8: STRENGTH. Weeks 9 to 12: STRENGTH + ATHLETICISM. Same lifts, different intent.",
             voice="Weeks one to four, recondition. Wake the body up. Weeks five to eight, add real load. Weeks nine to twelve, layer in power for cricket. Same lifts, sharper intent.", duration=12),
        _blk("say", heading="SAFETY FIRST", body="If a joint hurts, stop the set. Warm up every session. Bracing matters more than the number on the bar. Do not train through pain in the low back, elbow, or knee.",
             voice="Safety first. If a joint hurts, stop the set. Warm up every session. Bracing matters more than the number on the bar. Soreness fades. Strains linger.", duration=10),
        _blk("ending", heading="LET'S BEGIN", sub="Open the calendar and pick your next session.", duration=6),
    ],
}

# ---------- WARM-UP + COOL-DOWN BLOCKS ----------
def _warmup_general():
    return [
        _blk("timed", name="Neck rolls", side="both", equipment="Bodyweight", work=30, rest=0,
             cues=["Slow half circles", "No forcing the range", "Breathe"],
             mistakes=["Rushing the movement"],
             safety="Stop if you feel any dizziness.",
             svg="neck", voice="Neck rolls. Slow half circles. Do not force the range."),
        _blk("timed", name="Shoulder rolls", equipment="Bodyweight", work=30, rest=0,
             cues=["Big backward circles", "Chest tall", "Relaxed jaw"],
             mistakes=["Shrugging into the ears"],
             safety="Move within a pain-free arc.",
             svg="shoulder", voice="Shoulder rolls backward. Chest tall. Nice big circles."),
        _blk("timed", name="Hip circles", equipment="Bodyweight", work=40, rest=0,
             cues=["Hands on hips", "Draw wide circles with the pelvis", "Feet planted"],
             mistakes=["Bending only at the knees"],
             safety="Keep the low back long.",
             svg="hip", voice="Hip circles. Draw the widest circle you can with the pelvis."),
        _blk("timed", name="Bodyweight squats", equipment="Bodyweight", work=45, rest=0,
             cues=["Sit between the ankles", "Chest proud", "Knees track over toes"],
             mistakes=["Knees caving in", "Rounding the low back"],
             safety="Only go as low as your ankles allow today.",
             svg="squat", voice="Bodyweight squats. Sit between the ankles. Chest proud. Wake the legs up."),
        _blk("timed", name="Glute bridges", equipment="Bodyweight", work=45, rest=0,
             cues=["Heels planted", "Squeeze glutes at the top", "Ribs down"],
             mistakes=["Overextending the low back"],
             safety="Push through the heels, not the toes.",
             svg="bridge", voice="Glute bridges. Heels planted. Squeeze the glutes at the top. Keep the ribs down."),
    ]


def _cooldown_general():
    return [
        _blk("timed", name="Cat-cow", equipment="Bodyweight", work=45, rest=0,
             cues=["Move with the breath", "Reach through the tailbone", "Soft elbows"],
             mistakes=["Rushing"],
             safety="Small ranges are fine.",
             svg="catcow", voice="Cat cow. Move with the breath. Small ranges are perfect."),
        _blk("timed", name="Child's pose", equipment="Bodyweight", work=45, rest=0,
             cues=["Knees wide", "Sit back into the heels", "Long arms"],
             mistakes=["Rounding hard into the neck"],
             safety="Rest the forehead on a folded towel if needed.",
             svg="child", voice="Child's pose. Sit back into the heels. Breathe into the ribs."),
        _blk("timed", name="Deep breathing", equipment="Bodyweight", work=60, rest=0,
             cues=["4 seconds in, 6 seconds out", "Belly rises first", "Shoulders quiet"],
             mistakes=["Chest-only breathing"],
             safety="No effort, just breathe.",
             svg="breath", voice="Deep breathing. Four seconds in. Six seconds out. Belly first. We are done."),
    ]


# ---------- SESSION 2: FULL BODY STRENGTH A ----------
SESSION_FBA = {
    "id": "full-body-a",
    "code": "S2",
    "title": "FULL BODY A",
    "subtitle": "Tuesday - Strength",
    "day": "TUE",
    "duration_min": 32,
    "color": "red",
    "blocks": [
        _blk("title", heading="FULL BODY A", sub="Tuesday - Strength", duration=5),
        _blk("say", heading="TODAY", body="Squat pattern. Row pattern. Overhead press. Curl finisher. Same weight, three sets, RIR 2 to 3.",
             voice="Today. Squat. Row. Overhead press. Curl. Three working sets on each. Same weight. Two to three reps in the tank.", duration=8),
        _blk("say", heading="WARM-UP", body="Five easy movements. Do each one, no rest between.",
             voice="Five easy movements to warm up. No rest between.", duration=5),
        *_warmup_general(),
        _blk("say", heading="MAIN LIFTS", body="Take a full breath, brace, then move.",
             voice="Main lifts. Take a full breath. Brace. Then move.", duration=5),
        _blk("exercise", name="Barbell Back Squat", equipment="5-ft straight bar + plates", sets=3, reps="8-10", rest=90,
             cues=["Bar on the traps, not the neck", "Feet slightly wider than hips", "Sit between the ankles", "Knees track over toes", "Drive the floor away"],
             mistakes=["Knees caving inward", "Chest collapsing forward", "Half-reps to protect the low back"],
             safety="No rack means you clean the bar onto the traps. If a rep feels ugly, dump the set and reset. Do not rescue a bad squat.",
             svg="squat_bar",
             voice="Barbell back squat. Three sets of eight to ten. Ninety seconds rest. Same weight across all three sets. Sit between the ankles. Drive the floor away."),
        _blk("exercise", name="Bent-Over Barbell Row", equipment="5-ft straight bar + plates", sets=3, reps="8-10", rest=90,
             cues=["Hips back, chest 45 degrees", "Bar drags up to lower ribs", "Squeeze shoulder blades together", "Neutral spine"],
             mistakes=["Rounding the lower back", "Yanking with the arms", "Torso bouncing up on every rep"],
             safety="If the low back rounds even a little, drop the weight. This lift lives or dies on a neutral spine.",
             svg="row_bar",
             voice="Bent over barbell row. Three sets of eight to ten. Ninety seconds rest. Hips back. Chest at forty five degrees. Pull the bar to the lower ribs. Squeeze the shoulder blades."),
        _blk("exercise", name="Standing Overhead Press", equipment="5-ft straight bar + plates", sets=3, reps="6-8", rest=90,
             cues=["Bar starts at the collarbone", "Squeeze glutes, brace core", "Press up, head through at lockout", "Feet grounded"],
             mistakes=["Leaning back into the low back", "Pressing in front of the body", "Loose midsection"],
             safety="If the low back arches to press, the weight is too heavy. Own the brace before you own the press.",
             svg="ohp_bar",
             voice="Standing overhead press. Three sets of six to eight. Ninety seconds rest. Squeeze the glutes. Brace the core. Press up. Head through at the top."),
        _blk("exercise", name="Barbell Curl", equipment="3-ft curl bar + plates", sets=3, reps="10-12", rest=60,
             cues=["Elbows pinned to ribs", "Curl the bar, not the shoulders", "Full stretch at the bottom", "Squeeze at the top"],
             mistakes=["Swinging the torso", "Elbows drifting forward"],
             safety="If elbows or wrists get grumpy, switch to the neutral dumbbell grip.",
             svg="curl_ez",
             voice="Barbell curl on the E Z bar. Three sets of ten to twelve. Sixty seconds rest. Elbows pinned. No swinging."),
        _blk("say", heading="COOL DOWN", body="Bring the heart rate down. Breathe.",
             voice="Cool down. Bring the heart rate down. Breathe.", duration=5),
        *_cooldown_general(),
        _blk("ending", heading="SESSION COMPLETE", sub="Log your weights. See you Thursday.", duration=6),
    ],
}


# ---------- SESSION 3: FULL BODY STRENGTH B ----------
SESSION_FBB = {
    "id": "full-body-b",
    "code": "S3",
    "title": "FULL BODY B",
    "subtitle": "Thursday - Strength",
    "day": "THU",
    "duration_min": 32,
    "color": "red",
    "blocks": [
        _blk("title", heading="FULL BODY B", sub="Thursday - Strength", duration=5),
        _blk("say", heading="TODAY", body="Hinge, floor press, reverse curl, shrug. Posterior chain, chest, grip.",
             voice="Today. Hinge pattern. Floor press. Reverse curl. Shrug. Posterior chain, chest, and grip.", duration=8),
        _blk("say", heading="WARM-UP", body="Same warm-up flow. Five movements, straight through.",
             voice="Same warm up. Five movements, straight through.", duration=5),
        *_warmup_general(),
        _blk("say", heading="MAIN LIFTS", body="Own the hinge. Own the brace.",
             voice="Main lifts. Own the hinge. Own the brace.", duration=5),
        _blk("exercise", name="Barbell Romanian Deadlift", equipment="5-ft straight bar + plates", sets=3, reps="8-10", rest=90,
             cues=["Soft knees, then locked", "Push the hips back, not down", "Bar hugs the thighs", "Feel the hamstrings load"],
             mistakes=["Turning it into a squat", "Rounding the low back at the bottom", "Bar drifting away from the legs"],
             safety="Stop at your hamstring range - usually mid-shin. Never round to chase depth.",
             svg="rdl_bar",
             voice="Romanian deadlift. Three sets of eight to ten. Ninety seconds rest. Push the hips back. Bar stays close to the legs. Feel the hamstrings load."),
        _blk("exercise", name="Barbell Floor Press", equipment="5-ft straight bar + plates", sets=3, reps="8-10", rest=90,
             cues=["Elbows tuck to 45 degrees", "Pause when triceps touch the floor", "Press to lockout without flaring", "Squeeze the chest"],
             mistakes=["Bouncing the elbows off the floor", "Flaring elbows wide"],
             safety="No spotter, no rack. Start with a weight you can control fully. Roll the bar off the belly if a rep fails.",
             svg="floorpress",
             voice="Barbell floor press. Three sets of eight to ten. Ninety seconds rest. Tuck the elbows. Pause when the triceps touch the floor. Press."),
        _blk("exercise", name="Reverse Curl", equipment="3-ft curl bar + plates", sets=3, reps="10-12", rest=60,
             cues=["Overhand grip", "Wrists straight", "Curl slowly", "Feel the top of the forearm"],
             mistakes=["Wrists breaking", "Using the shoulders"],
             safety="Go lighter than a regular curl. Grip and wrist first.",
             svg="rcurl_ez",
             voice="Reverse curl. Three sets of ten to twelve. Sixty seconds rest. Overhand grip. Wrists straight. Slow and controlled."),
        _blk("exercise", name="Barbell Shrug", equipment="5-ft straight bar + plates", sets=3, reps="10-12", rest=60,
             cues=["Bar in front, arms long", "Shrug straight up to the ears", "Hold for one second at the top", "Lower slowly"],
             mistakes=["Rolling the shoulders", "Using the biceps"],
             safety="Straight up and down. No shoulder rolls - they annoy the AC joint.",
             svg="shrug",
             voice="Barbell shrug. Three sets of ten to twelve. Sixty seconds rest. Straight up. Hold one second. Lower slow."),
        _blk("say", heading="COOL DOWN", body="Long exhales. Wind it down.",
             voice="Cool down. Long exhales. Wind it down.", duration=5),
        *_cooldown_general(),
        _blk("ending", heading="SESSION COMPLETE", sub="Two strength days in the bank. Log it.", duration=6),
    ],
}


# ---------- SESSION 4: MOBILITY + CORE ----------
SESSION_MOB = {
    "id": "mobility-core",
    "code": "S4",
    "title": "MOBILITY + CORE",
    "subtitle": "Friday - Reset",
    "day": "FRI",
    "duration_min": 22,
    "color": "teal",
    "blocks": [
        _blk("title", heading="MOBILITY + CORE", sub="Friday - Reset", duration=5),
        _blk("say", heading="TODAY", body="Open the hips, calm the low back, wake up the deep core. Prep the body for cricket.",
             voice="Today. Open the hips. Calm the low back. Wake up the deep core. Prep the body for cricket.", duration=8),
        _blk("timed", name="World's Greatest Stretch", equipment="Bodyweight", work=60, rest=15,
             cues=["Long lunge", "Same-side hand to the floor", "Rotate the top arm up and open", "Both sides"],
             mistakes=["Rushing the rotation"],
             safety="Move slowly. This is a mobility drill, not a race.",
             svg="wgs", voice="World's greatest stretch. Long lunge. Rotate the top arm up. Both sides."),
        _blk("timed", name="90/90 Hip Switch", equipment="Bodyweight", work=60, rest=15,
             cues=["Sit tall", "Front leg 90, back leg 90", "Rotate both knees to the other side", "Chest up"],
             mistakes=["Collapsing the chest"],
             safety="Only go as far as the hips allow today.",
             svg="hip9090", voice="Ninety ninety hip switch. Sit tall. Rotate both knees side to side."),
        _blk("timed", name="Thoracic Book Opener", equipment="Bodyweight", work=45, rest=15,
             cues=["Side-lying, top knee bent", "Top arm sweeps open like a page", "Follow with the eyes"],
             mistakes=["Forcing the range"],
             safety="Small range is fine.",
             svg="tspine", voice="Thoracic book opener. Sweep the top arm open. Follow with the eyes."),
        _blk("say", heading="CORE CIRCUIT x 3", body="Three rounds. No rest inside a round. Sixty seconds between rounds.",
             voice="Core circuit. Three rounds. No rest inside a round. Sixty seconds between rounds.", duration=6),
        _blk("timed", name="Dead Bug", equipment="Bodyweight", work=40, rest=0,
             cues=["Low back glued to the floor", "Opposite arm and leg lower slow", "Exhale on the way down"],
             mistakes=["Low back arching off the floor"],
             safety="Stop if the low back lifts.",
             svg="deadbug", voice="Dead bug. Low back stays glued to the floor. Slow and controlled."),
        _blk("timed", name="Plank", equipment="Bodyweight", work=40, rest=0,
             cues=["Straight line ear to ankle", "Squeeze glutes", "Ribs down"],
             mistakes=["Hips sagging", "Hips piking up"],
             safety="Drop to knees if the low back complains.",
             svg="plank", voice="Plank. Straight line. Squeeze the glutes. Ribs down."),
        _blk("timed", name="Side Plank (each side)", equipment="Bodyweight", work=30, rest=0,
             cues=["Stack the feet", "Hips up high", "Reach the top arm to the sky"],
             mistakes=["Hips dropping"],
             safety="Elbow directly under the shoulder.",
             svg="sideplank", voice="Side plank. Both sides. Hips up high. Reach the top arm."),
        _blk("timed", name="Hollow Hold", equipment="Bodyweight", work=25, rest=60,
             cues=["Low back pressed down", "Arms and legs extend", "Small banana shape"],
             mistakes=["Low back peeling off the floor"],
             safety="Tuck the knees if the low back lifts.",
             svg="hollow", voice="Hollow hold. Low back pressed down. Small banana shape."),
        _blk("timed", name="Round 2 - Dead Bug", equipment="Bodyweight", work=40, rest=0, cues=["Same as round one"], mistakes=[], safety="", svg="deadbug", voice="Round two. Dead bug."),
        _blk("timed", name="Round 2 - Plank", equipment="Bodyweight", work=40, rest=0, cues=[], mistakes=[], safety="", svg="plank", voice="Plank."),
        _blk("timed", name="Round 2 - Side Plank", equipment="Bodyweight", work=30, rest=0, cues=[], mistakes=[], safety="", svg="sideplank", voice="Side plank both sides."),
        _blk("timed", name="Round 2 - Hollow Hold", equipment="Bodyweight", work=25, rest=60, cues=[], mistakes=[], safety="", svg="hollow", voice="Hollow hold. One round to go."),
        _blk("timed", name="Round 3 - Dead Bug", equipment="Bodyweight", work=40, rest=0, cues=[], mistakes=[], safety="", svg="deadbug", voice="Final round. Dead bug."),
        _blk("timed", name="Round 3 - Plank", equipment="Bodyweight", work=40, rest=0, cues=[], mistakes=[], safety="", svg="plank", voice="Plank. Almost there."),
        _blk("timed", name="Round 3 - Side Plank", equipment="Bodyweight", work=30, rest=0, cues=[], mistakes=[], safety="", svg="sideplank", voice="Side plank both sides."),
        _blk("timed", name="Round 3 - Hollow Hold", equipment="Bodyweight", work=25, rest=0, cues=[], mistakes=[], safety="", svg="hollow", voice="Last hollow hold. Finish strong."),
        _blk("say", heading="COOL DOWN", body="Long, slow breaths.",
             voice="Cool down. Long slow breaths.", duration=4),
        *_cooldown_general(),
        _blk("ending", heading="RESET DONE", sub="Hips open, core awake. Cricket-ready.", duration=6),
    ],
}


# ---------- SESSION 5: CRICKET DAY ----------
SESSION_CRICKET = {
    "id": "cricket-day",
    "code": "S5",
    "title": "CRICKET DAY",
    "subtitle": "Match Warm-up + Cool-down",
    "day": "SAT",
    "duration_min": 16,
    "color": "green",
    "blocks": [
        _blk("title", heading="CRICKET DAY", sub="Warm-up + Cool-down", duration=5),
        _blk("say", heading="MATCH-DAY READINESS", body="Before you play, run through the checklist. Slept well? Hydrated? Any sharp pain? Be honest.",
             voice="Before you play, run through the match day checklist. Sleep. Hydration. Any sharp pain. Be honest with yourself.", duration=8),
        _blk("checklist", heading="MATCH-DAY CHECKLIST", items=[
            "Slept 6+ hours last night",
            "Hydrated in the last hour",
            "No sharp pain in shoulder, low back, or knees",
            "Eaten a light meal 60-90 min ago",
            "Cricket kit + sunscreen packed",
        ], duration=20),
        _blk("say", heading="PRE-MATCH WARM-UP", body="Eight minutes. Dynamic, sport-specific. Do it on the ground, not in the car park.",
             voice="Pre match warm up. Eight minutes. Dynamic. Do it on the ground, not in the car park.", duration=8),
        _blk("timed", name="Easy Jog", equipment="Bodyweight", work=60, rest=0,
             cues=["Relaxed pace", "Nose breathing", "Shake the arms out"],
             mistakes=["Going too hard"],
             safety="Just wake the system up.",
             svg="jog", voice="Easy jog in place or a short loop. Relaxed pace. Nose breathing."),
        _blk("timed", name="Leg Swings (each leg)", equipment="Bodyweight", work=45, rest=0,
             cues=["Front to back, then side to side", "Small to big range", "Hold something for balance"],
             mistakes=["Kicking too hard cold"],
             safety="Start small, build the range.",
             svg="legswing", voice="Leg swings. Both legs. Front to back. Then side to side."),
        _blk("timed", name="World's Greatest Stretch", equipment="Bodyweight", work=60, rest=0,
             cues=["Both sides", "Rotate the top arm up"],
             mistakes=[],
             safety="Move with control.",
             svg="wgs", voice="World's greatest stretch. Both sides."),
        _blk("timed", name="Arm Circles + Cross-Body", equipment="Bodyweight", work=45, rest=0,
             cues=["Big circles forward and backward", "Cross-body sweeps"],
             mistakes=["Neck creeping up"],
             safety="Warm the shoulder before any throws.",
             svg="armcircle", voice="Arm circles forward and backward. Then cross body sweeps. Warm the shoulder before any throws."),
        _blk("timed", name="Walking Lunges", equipment="Bodyweight", work=60, rest=0,
             cues=["Long step", "Back knee kisses the ground", "Chest tall"],
             mistakes=["Short choppy steps"],
             safety="Slow first, then add tempo.",
             svg="lunge", voice="Walking lunges. Long step. Chest tall."),
        _blk("timed", name="Mock Bat Swings", equipment="Bat (optional)", work=45, rest=0,
             cues=["Half-speed first", "Full swing after 10 reps", "Both stances if you switch-hit"],
             mistakes=["Full-power swings while still cold"],
             safety="Ramp up. Never max effort cold.",
             svg="batswing", voice="Mock bat swings. Half speed first. Then full swing. Ramp up. Never max effort cold."),
        _blk("timed", name="Mock Throw / Bowl", equipment="Bodyweight", work=60, rest=0,
             cues=["Short easy throws first", "Build to full effort over 6-8 reps", "Feel the shoulder open"],
             mistakes=["First throw at full effort"],
             safety="This is where most weekend shoulder injuries happen. Ramp up.",
             svg="throw", voice="Mock throw or bowl. Short easy throws first. Build to full effort over six to eight reps. This is where most weekend shoulder injuries happen. Ramp up."),
        _blk("say", heading="GO PLAY", body="You're warm. Have fun out there.",
             voice="You are warm. Go play. Have fun out there.", duration=6),
        _blk("say", heading="POST-MATCH COOL-DOWN", body="Do this after the match, on the boundary. Eight minutes. Future-you will thank you.",
             voice="After the match. On the boundary. Eight minutes. Future you will thank you.", duration=8),
        _blk("timed", name="Walking Cooldown", equipment="Bodyweight", work=90, rest=0,
             cues=["Slow walk", "Hands on hips", "Long exhales"],
             mistakes=["Sitting straight down"],
             safety="Keep moving until the heart rate settles.",
             svg="walk", voice="Slow walking cooldown. Keep moving until the heart rate settles."),
        _blk("timed", name="Standing Hamstring Stretch", equipment="Bodyweight", work=45, rest=0,
             cues=["Both legs", "Hinge from the hip", "Do not force"],
             mistakes=["Bouncing"],
             safety="Static, not bouncing.",
             svg="hamstretch", voice="Standing hamstring stretch. Both legs. Static. No bouncing."),
        _blk("timed", name="Hip Flexor Stretch (each side)", equipment="Bodyweight", work=45, rest=0,
             cues=["Half-kneeling", "Squeeze the back glute", "Tall chest"],
             mistakes=["Front knee caving in"],
             safety="If a knee is grumpy, pad it.",
             svg="hipflex", voice="Hip flexor stretch. Half kneeling. Squeeze the back glute. Tall chest."),
        _blk("timed", name="Calf Stretch (each side)", equipment="Bodyweight", work=40, rest=0,
             cues=["Back leg straight", "Heel down", "Lean into the front"],
             mistakes=["Back heel lifting"],
             safety="Bat-day calves love this.",
             svg="calf", voice="Calf stretch. Back heel stays down. Both sides."),
        _blk("timed", name="Cross-Body Shoulder", equipment="Bodyweight", work=30, rest=0,
             cues=["Pull arm across the chest", "Both arms", "Long neck"],
             mistakes=["Yanking on the elbow"],
             safety="Firm, not painful.",
             svg="crossshoulder", voice="Cross body shoulder stretch. Both arms. Firm, not painful."),
        _blk("timed", name="Chest Opener", equipment="Bodyweight", work=40, rest=0,
             cues=["Hands behind the back", "Chest up", "Long breath in"],
             mistakes=["Cranking the shoulders"],
             safety="Small range, deep breaths.",
             svg="chestopen", voice="Chest opener. Hands behind the back. Chest up. Long breath in."),
        _blk("ending", heading="MATCH DONE", sub="Refuel, hydrate, sleep. Recovery starts now.", duration=8),
    ],
}


ALL_SESSIONS = [SESSION_INTRO, SESSION_FBA, SESSION_FBB, SESSION_MOB, SESSION_CRICKET]
